<?php 
require_once(ROUTE_DIR.'lib/session.php');
require_once(ROUTE_DIR.'lib/autorisation.php');
require_once(ROUTE_DIR.'lib/validator.php');
require_once(ROUTE_DIR.'lib/upload.php');
require_once(ROUTE_DIR.'lib/database.php');
require_once(ROUTE_DIR.'models/medecin.models.php');
require_once(ROUTE_DIR.'models/patient.models.php');
require_once(ROUTE_DIR.'models/responsable.prestation.models.php');
require_once(ROUTE_DIR.'models/secretaire.models.php');
?>